
app: proxy

server:
  ip: # nat.cutenss.com
  port: 12341
  apiPort: 12351

auth:
  key: axingjwt12341
  expireInterval: 86400

client:
  userId: 1

http:
  port: 13333

grpc:
  port: 14444

mysql: 
  dsn: axing:axing@tcp(localhost:3306)/axing?charset=utf8&parseTime=true
