
app: proxy

server:
  ip: nat.cutenss.com
  port: 21234

auth:
  key: axingjwt12341
  expireInterval: 86400

client:
  userId: 1
  port: 21237

http:
  port: 21235

grpc:
  port: 21236

mysql: 
  dsn: axing:axing@tcp(localhost:3306)/axing?charset=utf8&parseTime=true
