// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: aa4445e0ef
// Version Date: 2021-11-05T10:39:36Z

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/ranxx/proxy/proto/clients/v1"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC ClientsServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.ClientsServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// clients

		listclient: grpctransport.NewServer(
			endpoints.ListClientEndpoint,
			DecodeGRPCListClientRequest,
			EncodeGRPCListClientResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the ClientsServer interface
type grpcServer struct {
	listclient grpctransport.Handler
}

// Methods for grpcServer to implement ClientsServer interface

func (s *grpcServer) ListClient(ctx context.Context, req *pb.ListClientReq) (*pb.ListClientRsp, error) {
	_, rep, err := s.listclient.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.ListClientRsp), nil
}

// Server Decode

// DecodeGRPCListClientRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC listclient request to a user-domain listclient request. Primarily useful in a server.
func DecodeGRPCListClientRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.ListClientReq)
	return req, nil
}

// Server Encode

// EncodeGRPCListClientResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain listclient response to a gRPC listclient reply. Primarily useful in a server.
func EncodeGRPCListClientResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.ListClientRsp)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
