// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: aa4445e0ef
// Version Date: 2021-11-05T10:39:36Z

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/ranxx/proxy/proto/transfers/v1"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC TransfersServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.TransfersServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// transfers

		listtransfer: grpctransport.NewServer(
			endpoints.ListTransferEndpoint,
			DecodeGRPCListTransferRequest,
			EncodeGRPCListTransferResponse,
			serverOptions...,
		),
		addtransfer: grpctransport.NewServer(
			endpoints.AddTransferEndpoint,
			DecodeGRPCAddTransferRequest,
			EncodeGRPCAddTransferResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the TransfersServer interface
type grpcServer struct {
	listtransfer grpctransport.Handler
	addtransfer  grpctransport.Handler
}

// Methods for grpcServer to implement TransfersServer interface

func (s *grpcServer) ListTransfer(ctx context.Context, req *pb.ListTransferReq) (*pb.ListTransferRsp, error) {
	_, rep, err := s.listtransfer.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.ListTransferRsp), nil
}

func (s *grpcServer) AddTransfer(ctx context.Context, req *pb.AddTransferReq) (*pb.AddTransferRsp, error) {
	_, rep, err := s.addtransfer.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.AddTransferRsp), nil
}

// Server Decode

// DecodeGRPCListTransferRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC listtransfer request to a user-domain listtransfer request. Primarily useful in a server.
func DecodeGRPCListTransferRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.ListTransferReq)
	return req, nil
}

// DecodeGRPCAddTransferRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC addtransfer request to a user-domain addtransfer request. Primarily useful in a server.
func DecodeGRPCAddTransferRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.AddTransferReq)
	return req, nil
}

// Server Encode

// EncodeGRPCListTransferResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain listtransfer response to a gRPC listtransfer reply. Primarily useful in a server.
func EncodeGRPCListTransferResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.ListTransferRsp)
	return resp, nil
}

// EncodeGRPCAddTransferResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain addtransfer response to a gRPC addtransfer reply. Primarily useful in a server.
func EncodeGRPCAddTransferResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.AddTransferRsp)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
