// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: aa4445e0ef
// Version Date: 2021-11-05T10:39:36Z

// Package grpc provides a gRPC client for the Transfers service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	"github.com/ranxx/proxy/kit/transfers/v1/svc"
	pb "github.com/ranxx/proxy/proto/transfers/v1"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.TransfersServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var listtransferEndpoint endpoint.Endpoint
	{
		listtransferEndpoint = grpctransport.NewClient(
			conn,
			"v1.Transfers",
			"ListTransfer",
			EncodeGRPCListTransferRequest,
			DecodeGRPCListTransferResponse,
			pb.ListTransferRsp{},
			clientOptions...,
		).Endpoint()
	}

	var addtransferEndpoint endpoint.Endpoint
	{
		addtransferEndpoint = grpctransport.NewClient(
			conn,
			"v1.Transfers",
			"AddTransfer",
			EncodeGRPCAddTransferRequest,
			DecodeGRPCAddTransferResponse,
			pb.AddTransferRsp{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		ListTransferEndpoint: listtransferEndpoint,
		AddTransferEndpoint:  addtransferEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCListTransferResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC listtransfer reply to a user-domain listtransfer response. Primarily useful in a client.
func DecodeGRPCListTransferResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.ListTransferRsp)
	return reply, nil
}

// DecodeGRPCAddTransferResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC addtransfer reply to a user-domain addtransfer response. Primarily useful in a client.
func DecodeGRPCAddTransferResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.AddTransferRsp)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCListTransferRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain listtransfer request to a gRPC listtransfer request. Primarily useful in a client.
func EncodeGRPCListTransferRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.ListTransferReq)
	return req, nil
}

// EncodeGRPCAddTransferRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain addtransfer request to a gRPC addtransfer request. Primarily useful in a client.
func EncodeGRPCAddTransferRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.AddTransferReq)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
