// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: aa4445e0ef
// Version Date: 2021-11-05T10:39:36Z

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/ranxx/proxy/proto/tunnels/v1"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC TunnelsServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.TunnelsServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// tunnels

		listtunnel: grpctransport.NewServer(
			endpoints.ListTunnelEndpoint,
			DecodeGRPCListTunnelRequest,
			EncodeGRPCListTunnelResponse,
			serverOptions...,
		),
		addtunnel: grpctransport.NewServer(
			endpoints.AddTunnelEndpoint,
			DecodeGRPCAddTunnelRequest,
			EncodeGRPCAddTunnelResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the TunnelsServer interface
type grpcServer struct {
	listtunnel grpctransport.Handler
	addtunnel  grpctransport.Handler
}

// Methods for grpcServer to implement TunnelsServer interface

func (s *grpcServer) ListTunnel(ctx context.Context, req *pb.ListTunnelReq) (*pb.ListTunnelRsp, error) {
	_, rep, err := s.listtunnel.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.ListTunnelRsp), nil
}

func (s *grpcServer) AddTunnel(ctx context.Context, req *pb.AddTunnelReq) (*pb.AddTunnelRsp, error) {
	_, rep, err := s.addtunnel.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.AddTunnelRsp), nil
}

// Server Decode

// DecodeGRPCListTunnelRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC listtunnel request to a user-domain listtunnel request. Primarily useful in a server.
func DecodeGRPCListTunnelRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.ListTunnelReq)
	return req, nil
}

// DecodeGRPCAddTunnelRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC addtunnel request to a user-domain addtunnel request. Primarily useful in a server.
func DecodeGRPCAddTunnelRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.AddTunnelReq)
	return req, nil
}

// Server Encode

// EncodeGRPCListTunnelResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain listtunnel response to a gRPC listtunnel reply. Primarily useful in a server.
func EncodeGRPCListTunnelResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.ListTunnelRsp)
	return resp, nil
}

// EncodeGRPCAddTunnelResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain addtunnel response to a gRPC addtunnel reply. Primarily useful in a server.
func EncodeGRPCAddTunnelResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.AddTunnelRsp)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
