// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: aa4445e0ef
// Version Date: 2021-11-05T10:39:36Z

// Package grpc provides a gRPC client for the Clients service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	"github.com/ranxx/proxy/kit/clients/v1/svc"
	pb "github.com/ranxx/proxy/proto/clients/v1"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.ClientsServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var listclientEndpoint endpoint.Endpoint
	{
		listclientEndpoint = grpctransport.NewClient(
			conn,
			"v1.Clients",
			"ListClient",
			EncodeGRPCListClientRequest,
			DecodeGRPCListClientResponse,
			pb.ListClientRsp{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		ListClientEndpoint: listclientEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCListClientResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC listclient reply to a user-domain listclient response. Primarily useful in a client.
func DecodeGRPCListClientResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.ListClientRsp)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCListClientRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain listclient request to a gRPC listclient request. Primarily useful in a client.
func EncodeGRPCListClientRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.ListClientReq)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
