// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: aa4445e0ef
// Version Date: 2021-11-05T10:39:36Z

package main

import (
	"flag"

	// This Service
	"github.com/ranxx/proxy/kit/clients/v1/handlers"
	"github.com/ranxx/proxy/kit/clients/v1/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	cfg := server.DefaultConfig
	cfg = handlers.SetConfig(cfg)

	server.Run(cfg)
}
